export const CREATE_NEW_BOARD = 'CREATE_NEW_BOARD';
export const SEND_OPEN_FLAG = 'SEND_OPEN_FLAG';
export const SEND_OPEN_FLAG_FALSE = 'SEND_OPEN_FLAG_FALSE';
export const TRANSITION_TEXT = 'TRANSITION_TEXT';
export const CLONE_ADD_LIST = 'CLONE_ADD_LIST';
export const CLEATE_ADD_LIST = 'CLEATE_ADD_LIST';
